Repository photopieproject/BE_Finally, pull requests merged in 2023-02, with the labels that each got.

#53 Fix- # 52 회원가입 시 휴대폰번호 등록 중복
  src/main/java/com/sparta/be_finally/config/errorcode/UserStatusCode.java
  src/main/java/com/sparta/be_finally/room/repository/RoomRepository.java
  src/main/java/com/sparta/be_finally/room/service/SchedulerService.java
  src/main/java/com/sparta/be_finally/user/repository/UserRepository.java
  src/main/java/com/sparta/be_finally/user/service/UserService.java
Labels: 🛠️fix

#58 Feat #56 - 완성된 사진 S3에 저장하는 기능 구현
  src/main/java/com/sparta/be_finally/config/S3/AwsS3Service.java
  src/main/java/com/sparta/be_finally/config/errorcode/CommonStatusCode.java
  src/main/java/com/sparta/be_finally/photo/controller/PhotoController.java
  src/main/java/com/sparta/be_finally/photo/dto/CompletePhotoRequestDto.java
  src/main/java/com/sparta/be_finally/photo/entity/Photo.java
  src/main/java/com/sparta/be_finally/photo/repository/PhotoRepository.java
  src/main/java/com/sparta/be_finally/photo/service/PhotoService.java
  src/main/java/com/sparta/be_finally/room/entity/Room.java
Labels: 🤩enhancement

#60 Feat #55 - 생성해둔 QRCode 가져오기
  build.gradle
  src/main/java/com/sparta/be_finally/config/errorcode/CommonStatusCode.java
  src/main/java/com/sparta/be_finally/config/validator/Validator.java
  src/main/java/com/sparta/be_finally/photo/controller/PhotoController.java
  src/main/java/com/sparta/be_finally/photo/entity/Photo.java
  src/main/java/com/sparta/be_finally/photo/repository/PhotoRepository.java
  src/main/java/com/sparta/be_finally/photo/service/PhotoService.java
  src/main/java/com/sparta/be_finally/room/controller/RoomController.java
  src/main/java/com/sparta/be_finally/room/repository/RoomRepository.java
  src/main/java/com/sparta/be_finally/room/service/RoomService.java
  src/main/java/com/sparta/be_finally/user/service/UserService.java
Labels: 🤩enhancement

#65 Refactor - 로그 추가 및 필요 없는 코드 삭제
  src/main/java/com/sparta/be_finally/config/AES256.java
  src/main/java/com/sparta/be_finally/photo/dto/FrameResponseDto.java
  src/main/java/com/sparta/be_finally/photo/entity/Photo.java
  src/main/java/com/sparta/be_finally/photo/repository/PhotoRepository.java
  src/main/java/com/sparta/be_finally/photo/service/PhotoService.java
  src/main/java/com/sparta/be_finally/room/controller/RoomController.java
  src/main/java/com/sparta/be_finally/room/repository/RoomParticipantRepository.java
  src/main/java/com/sparta/be_finally/room/service/RoomService.java
  src/main/java/com/sparta/be_finally/room/service/SchedulerService.java
  src/main/java/com/sparta/be_finally/user/service/UserService.java
Labels: refactor

#66 Refactor - 로그 추가 및 필요 없는 코드 삭제
  src/main/java/com/sparta/be_finally/user/dto/KakaoFriendListResponseDto.java
  src/main/java/com/sparta/be_finally/user/dto/KakaoFriendResponseDto.java
  src/main/java/com/sparta/be_finally/user/repository/UserRepository.java
  src/main/java/com/sparta/be_finally/user/service/UserService.java
Labels: refactor

#86 Fix #85 - 최대 인원 수 리턴 값 수정
  src/main/java/com/sparta/be_finally/room/service/RoomService.java
Labels: 🛠️fix

#89 Feat #75 - email 본인확인 기능 구현
  build.gradle
  src/main/java/com/sparta/be_finally/common/errorcode/UserStatusCode.java
  src/main/java/com/sparta/be_finally/config/EmailConfig.java
  src/main/java/com/sparta/be_finally/user/controller/UserController.java
  src/main/java/com/sparta/be_finally/user/dto/EmailConfirmRequestDto.java
  src/main/java/com/sparta/be_finally/user/entity/User.java
  src/main/java/com/sparta/be_finally/user/service/UserService.java
Labels: 🛠️fix
